version: "3.9"
   
services:
  backend:
    build:
      context: backend
    tty: true
    entrypoint: python manage.py runserver 0.0.0.0:8000
    environment:
      - PORT=8000
      - SECRET_KEY=ThisShouldBeSecret
      - DEBUG=True
    volumes:
      - ./backend/:/backend

  nginx:
    image: nginx:1.21.6-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - backend
      # - frontend
